export const fakeCurrencies = [
    {
        "code": "AFN",
        "type": "fiat",
        "caption": "AFN",
        "name": "Afghan Afghani",
        "symbol": "AFN",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "ALL",
        "type": "fiat",
        "caption": "ALL",
        "name": "Albanian Lek",
        "symbol": "ALL",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "DZD",
        "type": "fiat",
        "caption": "DZD",
        "name": "Algerian Dinar",
        "symbol": "DZD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ADP",
        "type": "fiat",
        "caption": "ADP",
        "name": "Andorran Peseta",
        "symbol": "ADP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "AOA",
        "type": "fiat",
        "caption": "AOA",
        "name": "Angolan Kwanza",
        "symbol": "AOA",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ARA",
        "type": "fiat",
        "caption": "ARA",
        "name": "Argentine Austral",
        "symbol": "ARA",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ARS",
        "type": "fiat",
        "caption": "ARS",
        "name": "Argentine Peso",
        "symbol": "ARS",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "AMD",
        "type": "fiat",
        "caption": "AMD",
        "name": "Armenian Dram",
        "symbol": "AMD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "AWG",
        "type": "fiat",
        "caption": "AWG",
        "name": "Aruban Florin",
        "symbol": "AWG",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "AUD",
        "type": "fiat",
        "caption": "AUD",
        "name": "Australian Dollar",
        "symbol": "A$",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ATS",
        "type": "fiat",
        "caption": "ATS",
        "name": "Austrian Schilling",
        "symbol": "ATS",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "AZN",
        "type": "fiat",
        "caption": "AZN",
        "name": "Azerbaijani Manat",
        "symbol": "AZN",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BSD",
        "type": "fiat",
        "caption": "BSD",
        "name": "Bahamian Dollar",
        "symbol": "BSD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BHD",
        "type": "fiat",
        "caption": "BHD",
        "name": "Bahraini Dinar",
        "symbol": "BHD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 3,
        "decimals": 3
    },
    {
        "code": "BDT",
        "type": "fiat",
        "caption": "BDT",
        "name": "Bangladeshi Taka",
        "symbol": "BDT",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BBD",
        "type": "fiat",
        "caption": "BBD",
        "name": "Barbadian Dollar",
        "symbol": "BBD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BYN",
        "type": "fiat",
        "caption": "BYN",
        "name": "Belarusian Ruble",
        "symbol": "BYN",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BEF",
        "type": "fiat",
        "caption": "BEF",
        "name": "Belgian Franc",
        "symbol": "BEF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BEC",
        "type": "fiat",
        "caption": "BEC",
        "name": "Belgian Franc (convertible)",
        "symbol": "BEC",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BEL",
        "type": "fiat",
        "caption": "BEL",
        "name": "Belgian Franc (financial)",
        "symbol": "BEL",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BZD",
        "type": "fiat",
        "caption": "BZD",
        "name": "Belize Dollar",
        "symbol": "BZD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BMD",
        "type": "fiat",
        "caption": "BMD",
        "name": "Bermudan Dollar",
        "symbol": "BMD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BTN",
        "type": "fiat",
        "caption": "BTN",
        "name": "Bhutanese Ngultrum",
        "symbol": "BTN",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "VED",
        "type": "fiat",
        "caption": "VED",
        "name": "Bol\u00edvar Soberano",
        "symbol": "VED",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BOB",
        "type": "fiat",
        "caption": "BOB",
        "name": "Bolivian Boliviano",
        "symbol": "BOB",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BOV",
        "type": "fiat",
        "caption": "BOV",
        "name": "Bolivian Mvdol",
        "symbol": "BOV",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BOP",
        "type": "fiat",
        "caption": "BOP",
        "name": "Bolivian Peso",
        "symbol": "BOP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BAM",
        "type": "fiat",
        "caption": "BAM",
        "name": "Bosnia-Herzegovina Convertible Mark",
        "symbol": "BAM",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BWP",
        "type": "fiat",
        "caption": "BWP",
        "name": "Botswanan Pula",
        "symbol": "BWP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BRL",
        "type": "fiat",
        "caption": "BRL",
        "name": "Brazilian Real",
        "symbol": "R$",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "GBP",
        "type": "fiat",
        "caption": "GBP",
        "name": "British Pound",
        "symbol": "\u00a3",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BND",
        "type": "fiat",
        "caption": "BND",
        "name": "Brunei Dollar",
        "symbol": "BND",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BGL",
        "type": "fiat",
        "caption": "BGL",
        "name": "Bulgarian Hard Lev",
        "symbol": "BGL",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BGN",
        "type": "fiat",
        "caption": "BGN",
        "name": "Bulgarian Lev",
        "symbol": "BGN",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BGM",
        "type": "fiat",
        "caption": "BGM",
        "name": "Bulgarian Socialist Lev",
        "symbol": "BGM",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BUK",
        "type": "fiat",
        "caption": "BUK",
        "name": "Burmese Kyat",
        "symbol": "BUK",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "BIF",
        "type": "fiat",
        "caption": "BIF",
        "name": "Burundian Franc",
        "symbol": "BIF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "KHR",
        "type": "fiat",
        "caption": "KHR",
        "name": "Cambodian Riel",
        "symbol": "KHR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "CAD",
        "type": "fiat",
        "caption": "CAD",
        "name": "Canadian Dollar",
        "symbol": "CA$",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "CVE",
        "type": "fiat",
        "caption": "CVE",
        "name": "Cape Verdean Escudo",
        "symbol": "CVE",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "KYD",
        "type": "fiat",
        "caption": "KYD",
        "name": "Cayman Islands Dollar",
        "symbol": "KYD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "XAF",
        "type": "fiat",
        "caption": "XAF",
        "name": "Central African CFA Franc",
        "symbol": "FCFA",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "XPF",
        "type": "fiat",
        "caption": "XPF",
        "name": "CFP Franc",
        "symbol": "CFPF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "CLE",
        "type": "fiat",
        "caption": "CLE",
        "name": "Chilean Escudo",
        "symbol": "CLE",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "CLP",
        "type": "fiat",
        "caption": "CLP",
        "name": "Chilean Peso",
        "symbol": "CLP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "CLF",
        "type": "fiat",
        "caption": "CLF",
        "name": "Chilean Unit of Account (UF)",
        "symbol": "CLF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 4,
        "decimals": 4
    },
    {
        "code": "CNX",
        "type": "fiat",
        "caption": "CNX",
        "name": "Chinese People\u2019s Bank Dollar",
        "symbol": "CNX",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "CNY",
        "type": "fiat",
        "caption": "CNY",
        "name": "Chinese Yuan",
        "symbol": "CN\u00a5",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "CNH",
        "type": "fiat",
        "caption": "CNH",
        "name": "Chinese Yuan (offshore)",
        "symbol": "CNH",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "COP",
        "type": "fiat",
        "caption": "COP",
        "name": "Colombian Peso",
        "symbol": "COP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "COU",
        "type": "fiat",
        "caption": "COU",
        "name": "Colombian Real Value Unit",
        "symbol": "COU",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "KMF",
        "type": "fiat",
        "caption": "KMF",
        "name": "Comorian Franc",
        "symbol": "KMF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "CDF",
        "type": "fiat",
        "caption": "CDF",
        "name": "Congolese Franc",
        "symbol": "CDF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "CRC",
        "type": "fiat",
        "caption": "CRC",
        "name": "Costa Rican Col\u00f3n",
        "symbol": "CRC",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "HRD",
        "type": "fiat",
        "caption": "HRD",
        "name": "Croatian Dinar",
        "symbol": "HRD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "HRK",
        "type": "fiat",
        "caption": "HRK",
        "name": "Croatian Kuna",
        "symbol": "HRK",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "CUC",
        "type": "fiat",
        "caption": "CUC",
        "name": "Cuban Convertible Peso",
        "symbol": "CUC",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "CUP",
        "type": "fiat",
        "caption": "CUP",
        "name": "Cuban Peso",
        "symbol": "CUP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "CYP",
        "type": "fiat",
        "caption": "CYP",
        "name": "Cypriot Pound",
        "symbol": "CYP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "CZK",
        "type": "fiat",
        "caption": "CZK",
        "name": "Czech Koruna",
        "symbol": "CZK",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "CSK",
        "type": "fiat",
        "caption": "CSK",
        "name": "Czechoslovak Hard Koruna",
        "symbol": "CSK",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "DKK",
        "type": "fiat",
        "caption": "DKK",
        "name": "Danish Krone",
        "symbol": "DKK",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "DJF",
        "type": "fiat",
        "caption": "DJF",
        "name": "Djiboutian Franc",
        "symbol": "DJF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "DOP",
        "type": "fiat",
        "caption": "DOP",
        "name": "Dominican Peso",
        "symbol": "DOP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "NLG",
        "type": "fiat",
        "caption": "NLG",
        "name": "Dutch Guilder",
        "symbol": "NLG",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "XCD",
        "type": "fiat",
        "caption": "XCD",
        "name": "East Caribbean Dollar",
        "symbol": "EC$",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "DDM",
        "type": "fiat",
        "caption": "DDM",
        "name": "East German Mark",
        "symbol": "DDM",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ECS",
        "type": "fiat",
        "caption": "ECS",
        "name": "Ecuadorian Sucre",
        "symbol": "ECS",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ECV",
        "type": "fiat",
        "caption": "ECV",
        "name": "Ecuadorian Unit of Constant Value",
        "symbol": "ECV",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "EGP",
        "type": "fiat",
        "caption": "EGP",
        "name": "Egyptian Pound",
        "symbol": "EGP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "GQE",
        "type": "fiat",
        "caption": "GQE",
        "name": "Equatorial Guinean Ekwele",
        "symbol": "GQE",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ERN",
        "type": "fiat",
        "caption": "ERN",
        "name": "Eritrean Nakfa",
        "symbol": "ERN",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "EEK",
        "type": "fiat",
        "caption": "EEK",
        "name": "Estonian Kroon",
        "symbol": "EEK",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ETB",
        "type": "fiat",
        "caption": "ETB",
        "name": "Ethiopian Birr",
        "symbol": "ETB",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "EUR",
        "type": "fiat",
        "caption": "EUR",
        "name": "Euro",
        "symbol": "\u20ac",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "XEU",
        "type": "fiat",
        "caption": "XEU",
        "name": "European Currency Unit",
        "symbol": "XEU",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "FKP",
        "type": "fiat",
        "caption": "FKP",
        "name": "Falkland Islands Pound",
        "symbol": "FKP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "FJD",
        "type": "fiat",
        "caption": "FJD",
        "name": "Fijian Dollar",
        "symbol": "FJD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "FIM",
        "type": "fiat",
        "caption": "FIM",
        "name": "Finnish Markka",
        "symbol": "FIM",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "FRF",
        "type": "fiat",
        "caption": "FRF",
        "name": "French Franc",
        "symbol": "FRF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "XFO",
        "type": "fiat",
        "caption": "XFO",
        "name": "French Gold Franc",
        "symbol": "XFO",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "XFU",
        "type": "fiat",
        "caption": "XFU",
        "name": "French UIC-Franc",
        "symbol": "XFU",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "GMD",
        "type": "fiat",
        "caption": "GMD",
        "name": "Gambian Dalasi",
        "symbol": "GMD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "GEK",
        "type": "fiat",
        "caption": "GEK",
        "name": "Georgian Kupon Larit",
        "symbol": "GEK",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "GEL",
        "type": "fiat",
        "caption": "GEL",
        "name": "Georgian Lari",
        "symbol": "GEL",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "DEM",
        "type": "fiat",
        "caption": "DEM",
        "name": "German Mark",
        "symbol": "DEM",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "GHS",
        "type": "fiat",
        "caption": "GHS",
        "name": "Ghanaian Cedi",
        "symbol": "GHS",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "GIP",
        "type": "fiat",
        "caption": "GIP",
        "name": "Gibraltar Pound",
        "symbol": "GIP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "GRD",
        "type": "fiat",
        "caption": "GRD",
        "name": "Greek Drachma",
        "symbol": "GRD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "GTQ",
        "type": "fiat",
        "caption": "GTQ",
        "name": "Guatemalan Quetzal",
        "symbol": "GTQ",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "GWP",
        "type": "fiat",
        "caption": "GWP",
        "name": "Guinea-Bissau Peso",
        "symbol": "GWP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "GNF",
        "type": "fiat",
        "caption": "GNF",
        "name": "Guinean Franc",
        "symbol": "GNF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "GNS",
        "type": "fiat",
        "caption": "GNS",
        "name": "Guinean Syli",
        "symbol": "GNS",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "GYD",
        "type": "fiat",
        "caption": "GYD",
        "name": "Guyanaese Dollar",
        "symbol": "GYD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "HTG",
        "type": "fiat",
        "caption": "HTG",
        "name": "Haitian Gourde",
        "symbol": "HTG",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "HNL",
        "type": "fiat",
        "caption": "HNL",
        "name": "Honduran Lempira",
        "symbol": "HNL",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "HKD",
        "type": "fiat",
        "caption": "HKD",
        "name": "Hong Kong Dollar",
        "symbol": "HK$",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "HUF",
        "type": "fiat",
        "caption": "HUF",
        "name": "Hungarian Forint",
        "symbol": "HUF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ISK",
        "type": "fiat",
        "caption": "ISK",
        "name": "Icelandic Kr\u00f3na",
        "symbol": "ISK",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "INR",
        "type": "fiat",
        "caption": "INR",
        "name": "Indian Rupee",
        "symbol": "\u20b9",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "IDR",
        "type": "fiat",
        "caption": "IDR",
        "name": "Indonesian Rupiah",
        "symbol": "IDR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "IRR",
        "type": "fiat",
        "caption": "IRR",
        "name": "Iranian Rial",
        "symbol": "IRR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "IQD",
        "type": "fiat",
        "caption": "IQD",
        "name": "Iraqi Dinar",
        "symbol": "IQD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "IEP",
        "type": "fiat",
        "caption": "IEP",
        "name": "Irish Pound",
        "symbol": "IEP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ILS",
        "type": "fiat",
        "caption": "ILS",
        "name": "Israeli New Shekel",
        "symbol": "\u20aa",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ILP",
        "type": "fiat",
        "caption": "ILP",
        "name": "Israeli Pound",
        "symbol": "ILP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ITL",
        "type": "fiat",
        "caption": "ITL",
        "name": "Italian Lira",
        "symbol": "ITL",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "JMD",
        "type": "fiat",
        "caption": "JMD",
        "name": "Jamaican Dollar",
        "symbol": "JMD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "JPY",
        "type": "fiat",
        "caption": "JPY",
        "name": "Japanese Yen",
        "symbol": "\u00a5",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "JOD",
        "type": "fiat",
        "caption": "JOD",
        "name": "Jordanian Dinar",
        "symbol": "JOD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 3,
        "decimals": 3
    },
    {
        "code": "KZT",
        "type": "fiat",
        "caption": "KZT",
        "name": "Kazakhstani Tenge",
        "symbol": "KZT",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "KES",
        "type": "fiat",
        "caption": "KES",
        "name": "Kenyan Shilling",
        "symbol": "KES",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "KWD",
        "type": "fiat",
        "caption": "KWD",
        "name": "Kuwaiti Dinar",
        "symbol": "KWD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 3,
        "decimals": 3
    },
    {
        "code": "KGS",
        "type": "fiat",
        "caption": "KGS",
        "name": "Kyrgystani Som",
        "symbol": "KGS",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "LAK",
        "type": "fiat",
        "caption": "LAK",
        "name": "Laotian Kip",
        "symbol": "LAK",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "LVL",
        "type": "fiat",
        "caption": "LVL",
        "name": "Latvian Lats",
        "symbol": "LVL",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "LVR",
        "type": "fiat",
        "caption": "LVR",
        "name": "Latvian Ruble",
        "symbol": "LVR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "LBP",
        "type": "fiat",
        "caption": "LBP",
        "name": "Lebanese Pound",
        "symbol": "LBP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "LSL",
        "type": "fiat",
        "caption": "LSL",
        "name": "Lesotho Loti",
        "symbol": "LSL",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "LRD",
        "type": "fiat",
        "caption": "LRD",
        "name": "Liberian Dollar",
        "symbol": "LRD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "LYD",
        "type": "fiat",
        "caption": "LYD",
        "name": "Libyan Dinar",
        "symbol": "LYD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 3,
        "decimals": 3
    },
    {
        "code": "LTL",
        "type": "fiat",
        "caption": "LTL",
        "name": "Lithuanian Litas",
        "symbol": "LTL",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "LTT",
        "type": "fiat",
        "caption": "LTT",
        "name": "Lithuanian Talonas",
        "symbol": "LTT",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "LUL",
        "type": "fiat",
        "caption": "LUL",
        "name": "Luxembourg Financial Franc",
        "symbol": "LUL",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "LUC",
        "type": "fiat",
        "caption": "LUC",
        "name": "Luxembourgian Convertible Franc",
        "symbol": "LUC",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "LUF",
        "type": "fiat",
        "caption": "LUF",
        "name": "Luxembourgian Franc",
        "symbol": "LUF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "MOP",
        "type": "fiat",
        "caption": "MOP",
        "name": "Macanese Pataca",
        "symbol": "MOP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MKD",
        "type": "fiat",
        "caption": "MKD",
        "name": "Macedonian Denar",
        "symbol": "MKD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MGA",
        "type": "fiat",
        "caption": "MGA",
        "name": "Malagasy Ariary",
        "symbol": "MGA",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "MGF",
        "type": "fiat",
        "caption": "MGF",
        "name": "Malagasy Franc",
        "symbol": "MGF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "MWK",
        "type": "fiat",
        "caption": "MWK",
        "name": "Malawian Kwacha",
        "symbol": "MWK",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MYR",
        "type": "fiat",
        "caption": "MYR",
        "name": "Malaysian Ringgit",
        "symbol": "MYR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MVR",
        "type": "fiat",
        "caption": "MVR",
        "name": "Maldivian Rufiyaa",
        "symbol": "MVR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MLF",
        "type": "fiat",
        "caption": "MLF",
        "name": "Malian Franc",
        "symbol": "MLF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MTL",
        "type": "fiat",
        "caption": "MTL",
        "name": "Maltese Lira",
        "symbol": "MTL",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MTP",
        "type": "fiat",
        "caption": "MTP",
        "name": "Maltese Pound",
        "symbol": "MTP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MRU",
        "type": "fiat",
        "caption": "MRU",
        "name": "Mauritanian Ouguiya",
        "symbol": "MRU",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MUR",
        "type": "fiat",
        "caption": "MUR",
        "name": "Mauritian Rupee",
        "symbol": "MUR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MXV",
        "type": "fiat",
        "caption": "MXV",
        "name": "Mexican Investment Unit",
        "symbol": "MXV",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MXN",
        "type": "fiat",
        "caption": "MXN",
        "name": "Mexican Peso",
        "symbol": "MX$",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MDC",
        "type": "fiat",
        "caption": "MDC",
        "name": "Moldovan Cupon",
        "symbol": "MDC",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MDL",
        "type": "fiat",
        "caption": "MDL",
        "name": "Moldovan Leu",
        "symbol": "MDL",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MCF",
        "type": "fiat",
        "caption": "MCF",
        "name": "Monegasque Franc",
        "symbol": "MCF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MNT",
        "type": "fiat",
        "caption": "MNT",
        "name": "Mongolian Tugrik",
        "symbol": "MNT",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MAD",
        "type": "fiat",
        "caption": "MAD",
        "name": "Moroccan Dirham",
        "symbol": "MAD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MAF",
        "type": "fiat",
        "caption": "MAF",
        "name": "Moroccan Franc",
        "symbol": "MAF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MZE",
        "type": "fiat",
        "caption": "MZE",
        "name": "Mozambican Escudo",
        "symbol": "MZE",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MZN",
        "type": "fiat",
        "caption": "MZN",
        "name": "Mozambican Metical",
        "symbol": "MZN",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "MMK",
        "type": "fiat",
        "caption": "MMK",
        "name": "Myanmar Kyat",
        "symbol": "MMK",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "NAD",
        "type": "fiat",
        "caption": "NAD",
        "name": "Namibian Dollar",
        "symbol": "NAD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "NPR",
        "type": "fiat",
        "caption": "NPR",
        "name": "Nepalese Rupee",
        "symbol": "NPR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ANG",
        "type": "fiat",
        "caption": "ANG",
        "name": "Netherlands Antillean Guilder",
        "symbol": "ANG",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "TWD",
        "type": "fiat",
        "caption": "TWD",
        "name": "New Taiwan Dollar",
        "symbol": "NT$",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "NZD",
        "type": "fiat",
        "caption": "NZD",
        "name": "New Zealand Dollar",
        "symbol": "NZ$",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "NIO",
        "type": "fiat",
        "caption": "NIO",
        "name": "Nicaraguan C\u00f3rdoba",
        "symbol": "NIO",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "NGN",
        "type": "fiat",
        "caption": "NGN",
        "name": "Nigerian Naira",
        "symbol": "NGN",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "KPW",
        "type": "fiat",
        "caption": "KPW",
        "name": "North Korean Won",
        "symbol": "KPW",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "NOK",
        "type": "fiat",
        "caption": "NOK",
        "name": "Norwegian Krone",
        "symbol": "NOK",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "OMR",
        "type": "fiat",
        "caption": "OMR",
        "name": "Omani Rial",
        "symbol": "OMR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 3,
        "decimals": 3
    },
    {
        "code": "PKR",
        "type": "fiat",
        "caption": "PKR",
        "name": "Pakistani Rupee",
        "symbol": "PKR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "PAB",
        "type": "fiat",
        "caption": "PAB",
        "name": "Panamanian Balboa",
        "symbol": "PAB",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "PGK",
        "type": "fiat",
        "caption": "PGK",
        "name": "Papua New Guinean Kina",
        "symbol": "PGK",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "PYG",
        "type": "fiat",
        "caption": "PYG",
        "name": "Paraguayan Guarani",
        "symbol": "PYG",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "PEI",
        "type": "fiat",
        "caption": "PEI",
        "name": "Peruvian Inti",
        "symbol": "PEI",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "PEN",
        "type": "fiat",
        "caption": "PEN",
        "name": "Peruvian Sol",
        "symbol": "PEN",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "PHP",
        "type": "fiat",
        "caption": "PHP",
        "name": "Philippine Peso",
        "symbol": "\u20b1",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "PLN",
        "type": "fiat",
        "caption": "PLN",
        "name": "Polish Zloty",
        "symbol": "PLN",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "PTE",
        "type": "fiat",
        "caption": "PTE",
        "name": "Portuguese Escudo",
        "symbol": "PTE",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "GWE",
        "type": "fiat",
        "caption": "GWE",
        "name": "Portuguese Guinea Escudo",
        "symbol": "GWE",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "QAR",
        "type": "fiat",
        "caption": "QAR",
        "name": "Qatari Rial",
        "symbol": "QAR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "RHD",
        "type": "fiat",
        "caption": "RHD",
        "name": "Rhodesian Dollar",
        "symbol": "RHD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "XRE",
        "type": "fiat",
        "caption": "XRE",
        "name": "RINET Funds",
        "symbol": "XRE",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "RON",
        "type": "fiat",
        "caption": "RON",
        "name": "Romanian Leu",
        "symbol": "RON",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "RUB",
        "type": "fiat",
        "caption": "RUB",
        "name": "Russian Ruble",
        "symbol": "RUB",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "RWF",
        "type": "fiat",
        "caption": "RWF",
        "name": "Rwandan Franc",
        "symbol": "RWF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "SVC",
        "type": "fiat",
        "caption": "SVC",
        "name": "Salvadoran Col\u00f3n",
        "symbol": "SVC",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "WST",
        "type": "fiat",
        "caption": "WST",
        "name": "Samoan Tala",
        "symbol": "WST",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "STN",
        "type": "fiat",
        "caption": "STN",
        "name": "S\u00e3o Tom\u00e9 & Pr\u00edncipe Dobra",
        "symbol": "STN",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "SAR",
        "type": "fiat",
        "caption": "SAR",
        "name": "Saudi Riyal",
        "symbol": "SAR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "RSD",
        "type": "fiat",
        "caption": "RSD",
        "name": "Serbian Dinar",
        "symbol": "RSD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "SCR",
        "type": "fiat",
        "caption": "SCR",
        "name": "Seychellois Rupee",
        "symbol": "SCR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "SLL",
        "type": "fiat",
        "caption": "SLL",
        "name": "Sierra Leonean Leone",
        "symbol": "SLL",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "SLE",
        "type": "fiat",
        "caption": "SLE",
        "name": "Sierra Leonean New Leone",
        "symbol": "SLE",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "SGD",
        "type": "fiat",
        "caption": "SGD",
        "name": "Singapore Dollar",
        "symbol": "SGD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "SKK",
        "type": "fiat",
        "caption": "SKK",
        "name": "Slovak Koruna",
        "symbol": "SKK",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "SIT",
        "type": "fiat",
        "caption": "SIT",
        "name": "Slovenian Tolar",
        "symbol": "SIT",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "SBD",
        "type": "fiat",
        "caption": "SBD",
        "name": "Solomon Islands Dollar",
        "symbol": "SBD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "SOS",
        "type": "fiat",
        "caption": "SOS",
        "name": "Somali Shilling",
        "symbol": "SOS",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "ZAR",
        "type": "fiat",
        "caption": "ZAR",
        "name": "South African Rand",
        "symbol": "ZAR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ZAL",
        "type": "fiat",
        "caption": "ZAL",
        "name": "South African Rand (financial)",
        "symbol": "ZAL",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "KRW",
        "type": "fiat",
        "caption": "KRW",
        "name": "South Korean Won",
        "symbol": "\u20a9",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "SSP",
        "type": "fiat",
        "caption": "SSP",
        "name": "South Sudanese Pound",
        "symbol": "SSP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "SUR",
        "type": "fiat",
        "caption": "SUR",
        "name": "Soviet Rouble",
        "symbol": "SUR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ESP",
        "type": "fiat",
        "caption": "ESP",
        "name": "Spanish Peseta",
        "symbol": "ESP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "ESA",
        "type": "fiat",
        "caption": "ESA",
        "name": "Spanish Peseta (A account)",
        "symbol": "ESA",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ESB",
        "type": "fiat",
        "caption": "ESB",
        "name": "Spanish Peseta (convertible account)",
        "symbol": "ESB",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "LKR",
        "type": "fiat",
        "caption": "LKR",
        "name": "Sri Lankan Rupee",
        "symbol": "LKR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "SHP",
        "type": "fiat",
        "caption": "SHP",
        "name": "St. Helena Pound",
        "symbol": "SHP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "SDG",
        "type": "fiat",
        "caption": "SDG",
        "name": "Sudanese Pound",
        "symbol": "SDG",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "SRD",
        "type": "fiat",
        "caption": "SRD",
        "name": "Surinamese Dollar",
        "symbol": "SRD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "SRG",
        "type": "fiat",
        "caption": "SRG",
        "name": "Surinamese Guilder",
        "symbol": "SRG",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "SZL",
        "type": "fiat",
        "caption": "SZL",
        "name": "Swazi Lilangeni",
        "symbol": "SZL",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "SEK",
        "type": "fiat",
        "caption": "SEK",
        "name": "Swedish Krona",
        "symbol": "SEK",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "CHF",
        "type": "fiat",
        "caption": "CHF",
        "name": "Swiss Franc",
        "symbol": "CHF",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "SYP",
        "type": "fiat",
        "caption": "SYP",
        "name": "Syrian Pound",
        "symbol": "SYP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "TJR",
        "type": "fiat",
        "caption": "TJR",
        "name": "Tajikistani Ruble",
        "symbol": "TJR",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "TJS",
        "type": "fiat",
        "caption": "TJS",
        "name": "Tajikistani Somoni",
        "symbol": "TJS",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "TZS",
        "type": "fiat",
        "caption": "TZS",
        "name": "Tanzanian Shilling",
        "symbol": "TZS",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "THB",
        "type": "fiat",
        "caption": "THB",
        "name": "Thai Baht",
        "symbol": "THB",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "TPE",
        "type": "fiat",
        "caption": "TPE",
        "name": "Timorese Escudo",
        "symbol": "TPE",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "TOP",
        "type": "fiat",
        "caption": "TOP",
        "name": "Tongan Pa\u02bbanga",
        "symbol": "TOP",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "TTD",
        "type": "fiat",
        "caption": "TTD",
        "name": "Trinidad & Tobago Dollar",
        "symbol": "TTD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "TND",
        "type": "fiat",
        "caption": "TND",
        "name": "Tunisian Dinar",
        "symbol": "TND",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 3,
        "decimals": 3
    },
    {
        "code": "TRY",
        "type": "fiat",
        "caption": "TRY",
        "name": "Turkish Lira",
        "symbol": "TRY",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "TMT",
        "type": "fiat",
        "caption": "TMT",
        "name": "Turkmenistani Manat",
        "symbol": "TMT",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "UGX",
        "type": "fiat",
        "caption": "UGX",
        "name": "Ugandan Shilling",
        "symbol": "UGX",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "UAH",
        "type": "fiat",
        "caption": "UAH",
        "name": "Ukrainian Hryvnia",
        "symbol": "UAH",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "UAK",
        "type": "fiat",
        "caption": "UAK",
        "name": "Ukrainian Karbovanets",
        "symbol": "UAK",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "AED",
        "type": "fiat",
        "caption": "AED",
        "name": "United Arab Emirates Dirham",
        "symbol": "AED",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "UYW",
        "type": "fiat",
        "caption": "UYW",
        "name": "Uruguayan Nominal Wage Index Unit",
        "symbol": "UYW",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 4,
        "decimals": 4
    },
    {
        "code": "UYU",
        "type": "fiat",
        "caption": "UYU",
        "name": "Uruguayan Peso",
        "symbol": "UYU",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "UYI",
        "type": "fiat",
        "caption": "UYI",
        "name": "Uruguayan Peso (Indexed Units)",
        "symbol": "UYI",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "USD",
        "type": "fiat",
        "caption": "USD",
        "name": "US Dollar",
        "symbol": "$",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "USN",
        "type": "fiat",
        "caption": "USN",
        "name": "US Dollar (Next day)",
        "symbol": "USN",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "USS",
        "type": "fiat",
        "caption": "USS",
        "name": "US Dollar (Same day)",
        "symbol": "USS",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "UZS",
        "type": "fiat",
        "caption": "UZS",
        "name": "Uzbekistani Som",
        "symbol": "UZS",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "VUV",
        "type": "fiat",
        "caption": "VUV",
        "name": "Vanuatu Vatu",
        "symbol": "VUV",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "VES",
        "type": "fiat",
        "caption": "VES",
        "name": "Venezuelan Bol\u00edvar",
        "symbol": "VES",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "VND",
        "type": "fiat",
        "caption": "VND",
        "name": "Vietnamese Dong",
        "symbol": "\u20ab",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "XOF",
        "type": "fiat",
        "caption": "XOF",
        "name": "West African CFA Franc",
        "symbol": "F\u202fCFA",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "CHE",
        "type": "fiat",
        "caption": "CHE",
        "name": "WIR Euro",
        "symbol": "CHE",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "CHW",
        "type": "fiat",
        "caption": "CHW",
        "name": "WIR Franc",
        "symbol": "CHW",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "YDD",
        "type": "fiat",
        "caption": "YDD",
        "name": "Yemeni Dinar",
        "symbol": "YDD",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "YER",
        "type": "fiat",
        "caption": "YER",
        "name": "Yemeni Rial",
        "symbol": "YER",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 0,
        "decimals": 0
    },
    {
        "code": "ZMW",
        "type": "fiat",
        "caption": "ZMW",
        "name": "Zambian Kwacha",
        "symbol": "ZMW",
        "token": null,
        "tokenVariant": null,
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "ADA",
        "type": "crypto",
        "caption": "ADA",
        "name": "ADA (Cardano)",
        "symbol": "ADA",
        "token": "ADA",
        "tokenVariant": "Cardano",
        "significantDecimals": 6,
        "decimals": 6
    },
    {
        "code": "ALGO",
        "type": "crypto",
        "caption": "ALGO",
        "name": "Algorand",
        "symbol": "ALGO",
        "token": "ALGO",
        "tokenVariant": "Algorand",
        "significantDecimals": 6,
        "decimals": 6
    },
    {
        "code": "APE",
        "type": "crypto",
        "caption": "APE",
        "name": "ApeCoin",
        "symbol": "APE",
        "token": "APE",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "AVAX",
        "type": "crypto",
        "caption": "AVAX",
        "name": "Avalanche (C-Chain)",
        "symbol": "AVAX",
        "token": "AVAX",
        "tokenVariant": "Avalanche",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "BAT",
        "type": "crypto",
        "caption": "BAT",
        "name": "Basic Attention Token",
        "symbol": "BAT",
        "token": "BAT",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "BCH",
        "type": "crypto",
        "caption": "BCH",
        "name": "Bitcoin Cash",
        "symbol": "BCH",
        "token": "BCH",
        "tokenVariant": "Bitcoin Cash",
        "significantDecimals": 8,
        "decimals": 8
    },
    {
        "code": "BDOT",
        "type": "crypto",
        "caption": "BDOT",
        "name": "Binance Wrapped DOT",
        "symbol": "BDOT",
        "token": "BDOT",
        "tokenVariant": "ERC20",
        "significantDecimals": 10,
        "decimals": 10
    },
    {
        "code": "BNB",
        "type": "crypto",
        "caption": "BNB (BSC)",
        "name": "Binance Coin (BSC)",
        "symbol": "BNB (BSC)",
        "token": "BNB",
        "tokenVariant": "Binance Smart Chain BSC",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "BNT",
        "type": "crypto",
        "caption": "BNT",
        "name": "Bancor",
        "symbol": "BNT",
        "token": "BNT",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "BTC",
        "type": "crypto",
        "caption": "BTC",
        "name": "Bitcoin",
        "symbol": "BTC",
        "token": "BTC",
        "tokenVariant": "Bitcoin",
        "significantDecimals": 8,
        "decimals": 8
    },
    {
        "code": "BUSD",
        "type": "crypto",
        "caption": "BUSD (ERC20)",
        "name": "Binance USD",
        "symbol": "BUSD (ERC20)",
        "token": "BUSD",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "BUSD.b",
        "type": "crypto",
        "caption": "BUSD (BEP20)",
        "name": "Binance-Peg BUSD (BSC)",
        "symbol": "BUSD (BEP20)",
        "token": "BUSD",
        "tokenVariant": "BEP20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "CAKE",
        "type": "crypto",
        "caption": "CAKE",
        "name": "PancakeSwap Token",
        "symbol": "CAKE",
        "token": "CAKE",
        "tokenVariant": "BEP20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "CELO",
        "type": "crypto",
        "caption": "CELO",
        "name": "Celo",
        "symbol": "CELO",
        "token": "CELO",
        "tokenVariant": "CELO",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "CHER",
        "type": "crypto",
        "caption": "CHER",
        "name": "Cherry Token",
        "symbol": "CHER",
        "token": "CHER",
        "tokenVariant": "BEP20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "COTI",
        "type": "crypto",
        "caption": "COTI",
        "name": "COTI Token",
        "symbol": "COTI",
        "token": "COTI",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "CVC",
        "type": "crypto",
        "caption": "CVC",
        "name": "Civic",
        "symbol": "CVC",
        "token": "CVC",
        "tokenVariant": "ERC20",
        "significantDecimals": 8,
        "decimals": 8
    },
    {
        "code": "DAI",
        "type": "crypto",
        "caption": "DAI (ERC20)",
        "name": "Dai",
        "symbol": "DAI (ERC20)",
        "token": "DAI",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "DAI.b",
        "type": "crypto",
        "caption": "DAI (BEP20)",
        "name": "Dai BSC Token",
        "symbol": "DAI (BEP20)",
        "token": "DAI",
        "tokenVariant": "BEP20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "DAI.p",
        "type": "crypto",
        "caption": "DAI (POLYGON)",
        "name": "(PoS) Dai Stablecoin",
        "symbol": "DAI (POLYGON)",
        "token": "DAI",
        "tokenVariant": "POLYGON",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "DASH",
        "type": "crypto",
        "caption": "DASH",
        "name": "Dash",
        "symbol": "DASH",
        "token": "DASH",
        "tokenVariant": "DASH",
        "significantDecimals": 8,
        "decimals": 8
    },
    {
        "code": "DGD",
        "type": "crypto",
        "caption": "DGD",
        "name": "Digix DAO",
        "symbol": "DGD",
        "token": "DGD",
        "tokenVariant": "ERC20",
        "significantDecimals": 9,
        "decimals": 9
    },
    {
        "code": "DGX",
        "type": "crypto",
        "caption": "DGX",
        "name": "Digix",
        "symbol": "DGX",
        "token": "DGX",
        "tokenVariant": "ERC20",
        "significantDecimals": 9,
        "decimals": 9
    },
    {
        "code": "DOGE",
        "type": "crypto",
        "caption": "DOGE",
        "name": "Doge Coin",
        "symbol": "DOGE",
        "token": "DOGE",
        "tokenVariant": "ERC20",
        "significantDecimals": 8,
        "decimals": 8
    },
    {
        "code": "DOT",
        "type": "crypto",
        "caption": "DOT",
        "name": "Polkadot",
        "symbol": "DOT",
        "token": "DOT",
        "tokenVariant": "Polkadot",
        "significantDecimals": 10,
        "decimals": 10
    },
    {
        "code": "DOT.b",
        "type": "crypto",
        "caption": "DOT (BEP20)",
        "name": "Binance-Peg Polkadot (BSC)",
        "symbol": "DOT (BEP20)",
        "token": "DOT",
        "tokenVariant": "BEP20",
        "significantDecimals": 10,
        "decimals": 10
    },
    {
        "code": "EOS",
        "type": "crypto",
        "caption": "EOS",
        "name": "EOS",
        "symbol": "EOS",
        "token": "EOS",
        "tokenVariant": "EOS",
        "significantDecimals": 8,
        "decimals": 8
    },
    {
        "code": "ETC",
        "type": "crypto",
        "caption": "ETC",
        "name": "Ethereum Classic",
        "symbol": "ETC",
        "token": "ETC",
        "tokenVariant": "Ethereum Classic",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "ETH",
        "type": "crypto",
        "caption": "ETH",
        "name": "Ethereum",
        "symbol": "ETH",
        "token": "ETH",
        "tokenVariant": "Ethereum",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "EURST",
        "type": "crypto",
        "caption": "EURST",
        "name": "EURST",
        "symbol": "EURST",
        "token": "EURST",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "FEI",
        "type": "crypto",
        "caption": "FEI",
        "name": "Fei USD",
        "symbol": "FEI",
        "token": "FEI",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "FIL",
        "type": "crypto",
        "caption": "FIL",
        "name": "Binance-Peg Filecoin",
        "symbol": "FIL",
        "token": "FIL",
        "tokenVariant": "BEP20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "GNT",
        "type": "crypto",
        "caption": "GNT",
        "name": "Golem",
        "symbol": "GNT",
        "token": "GNT",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "GUSD",
        "type": "crypto",
        "caption": "GUSD",
        "name": "Gemini USD",
        "symbol": "GUSD",
        "token": "GUSD",
        "tokenVariant": "ERC20",
        "significantDecimals": 2,
        "decimals": 2
    },
    {
        "code": "LINK",
        "type": "crypto",
        "caption": "LINK",
        "name": "ChainLink",
        "symbol": "LINK",
        "token": "LINK",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "LRC",
        "type": "crypto",
        "caption": "LRC",
        "name": "Loopring",
        "symbol": "LRC",
        "token": "LRC",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "LTC",
        "type": "crypto",
        "caption": "LTC",
        "name": "Litecoin",
        "symbol": "LTC",
        "token": "LTC",
        "tokenVariant": "Litecoin",
        "significantDecimals": 8,
        "decimals": 8
    },
    {
        "code": "LUNA",
        "type": "crypto",
        "caption": "LUNA",
        "name": "Terra Classic Luna",
        "symbol": "LUNA",
        "token": "LUNA",
        "tokenVariant": "Terra",
        "significantDecimals": 6,
        "decimals": 6
    },
    {
        "code": "LUNA2",
        "type": "crypto",
        "caption": "LUNA2",
        "name": "Terra Luna 2.0",
        "symbol": "LUNA2",
        "token": "LUNA2",
        "tokenVariant": "Terra 2",
        "significantDecimals": 6,
        "decimals": 6
    },
    {
        "code": "LYO",
        "type": "crypto",
        "caption": "LYO",
        "name": "LYO Credit",
        "symbol": "LYO",
        "token": "LYO",
        "tokenVariant": "BEP20",
        "significantDecimals": 8,
        "decimals": 8
    },
    {
        "code": "MATIC",
        "type": "crypto",
        "caption": "MATIC",
        "name": "Matic Gas Token (Polygon)",
        "symbol": "MATIC",
        "token": "MATIC",
        "tokenVariant": "Polygon",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "MKR",
        "type": "crypto",
        "caption": "MKR",
        "name": "Maker",
        "symbol": "MKR",
        "token": "MKR",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "OMG",
        "type": "crypto",
        "caption": "OMG",
        "name": "OmiseGO Token",
        "symbol": "OMG",
        "token": "OMG",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "PAX",
        "type": "crypto",
        "caption": "PAX",
        "name": "PAX Dollar",
        "symbol": "PAX",
        "token": "PAX",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "PAXG",
        "type": "crypto",
        "caption": "PAXG",
        "name": "Paxos Gold",
        "symbol": "PAXG",
        "token": "PAXG",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "PPT",
        "type": "crypto",
        "caption": "PPT",
        "name": "Populous Platform",
        "symbol": "PPT",
        "token": "PPT",
        "tokenVariant": "ERC20",
        "significantDecimals": 8,
        "decimals": 8
    },
    {
        "code": "REP",
        "type": "crypto",
        "caption": "REP",
        "name": "Augur",
        "symbol": "REP",
        "token": "REP",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "SNT",
        "type": "crypto",
        "caption": "SNT",
        "name": "Status Network Token",
        "symbol": "SNT",
        "token": "SNT",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "SOL",
        "type": "crypto",
        "caption": "SOL",
        "name": "Solana",
        "symbol": "SOL",
        "token": "SOL",
        "tokenVariant": "Solana",
        "significantDecimals": 9,
        "decimals": 9
    },
    {
        "code": "STDOT",
        "type": "crypto",
        "caption": "STDOT",
        "name": "stakedDOT",
        "symbol": "STDOT",
        "token": "STDOT",
        "tokenVariant": "ERC20",
        "significantDecimals": 10,
        "decimals": 10
    },
    {
        "code": "TRX",
        "type": "crypto",
        "caption": "TRX",
        "name": "Tron TRX",
        "symbol": "TRX",
        "token": "TRX",
        "tokenVariant": "Tron",
        "significantDecimals": 6,
        "decimals": 6
    },
    {
        "code": "TUSD",
        "type": "crypto",
        "caption": "TUSD",
        "name": "TrueUSD",
        "symbol": "TUSD",
        "token": "TUSD",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "UNI",
        "type": "crypto",
        "caption": "UNI",
        "name": "Uniswap Token",
        "symbol": "UNI",
        "token": "UNI",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "USDC",
        "type": "crypto",
        "caption": "USDC (ERC20)",
        "name": "USD Coin (Ethereum)",
        "symbol": "USDC (ERC20)",
        "token": "USDC",
        "tokenVariant": "ERC20",
        "significantDecimals": 6,
        "decimals": 6
    },
    {
        "code": "USDC.t",
        "type": "crypto",
        "caption": "USDC (TRC20)",
        "name": "USD Coin (Tron)",
        "symbol": "USDC (TRC20)",
        "token": "USDC",
        "tokenVariant": "Tron",
        "significantDecimals": 6,
        "decimals": 6
    },
    {
        "code": "USDD",
        "type": "crypto",
        "caption": "USDD",
        "name": "USD Digital",
        "symbol": "USDD",
        "token": "USDD",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "USDT",
        "type": "crypto",
        "caption": "USDT (ERC20)",
        "name": "Tether USD (Ethereum)",
        "symbol": "USDT (ERC20)",
        "token": "USDT",
        "tokenVariant": "ERC20",
        "significantDecimals": 6,
        "decimals": 6
    },
    {
        "code": "USDT.b",
        "type": "crypto",
        "caption": "USDT (BEP20)",
        "name": "Binance-Peg Tether (BSC)",
        "symbol": "USDT (BEP20)",
        "token": "USDT",
        "tokenVariant": "BEP20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "USDT.p",
        "type": "crypto",
        "caption": "USDT (POLYGON)",
        "name": "(PoS) Tether USD (Polygon)",
        "symbol": "USDT (POLYGON)",
        "token": "USDT",
        "tokenVariant": "Polygon",
        "significantDecimals": 6,
        "decimals": 6
    },
    {
        "code": "USDT.t",
        "type": "crypto",
        "caption": "USDT (TRC20)",
        "name": "USD Tether (Tron)",
        "symbol": "USDT (TRC20)",
        "token": "USDT",
        "tokenVariant": "TRC20",
        "significantDecimals": 6,
        "decimals": 6
    },
    {
        "code": "WAVES",
        "type": "crypto",
        "caption": "WAVES",
        "name": "WAVES token",
        "symbol": "WAVES",
        "token": "WAVES",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "WBTC",
        "type": "crypto",
        "caption": "WBTC",
        "name": "Wrapped Bitcoin",
        "symbol": "WBTC",
        "token": "WBTC",
        "tokenVariant": "ERC20",
        "significantDecimals": 8,
        "decimals": 8
    },
    {
        "code": "WLUNA",
        "type": "crypto",
        "caption": "WLUNA",
        "name": "Wrapped LUNA Token",
        "symbol": "WLUNA",
        "token": "WLUNA",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "WLXT",
        "type": "crypto",
        "caption": "WLXT",
        "name": "Wallex Token",
        "symbol": "WLXT",
        "token": "WLXT",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    },
    {
        "code": "XLM",
        "type": "crypto",
        "caption": "XLM",
        "name": "Stellar",
        "symbol": "XLM",
        "token": "XLM",
        "tokenVariant": "Stellar",
        "significantDecimals": 7,
        "decimals": 7
    },
    {
        "code": "XRP",
        "type": "crypto",
        "caption": "XRP",
        "name": "Ripple",
        "symbol": "XRP",
        "token": "XRP",
        "tokenVariant": "Ripple",
        "significantDecimals": 6,
        "decimals": 6
    },
    {
        "code": "XTZ",
        "type": "crypto",
        "caption": "XTZ",
        "name": "Tezos",
        "symbol": "XTZ",
        "token": "XTZ",
        "tokenVariant": "Tezos",
        "significantDecimals": 6,
        "decimals": 6
    },
    {
        "code": "ZRX",
        "type": "crypto",
        "caption": "ZRX",
        "name": "0x Token",
        "symbol": "ZRX",
        "token": "ZRX",
        "tokenVariant": "ERC20",
        "significantDecimals": 16,
        "decimals": 18
    }
]